"""Layer 2: derive an Allen constraint network from a built document and test it.

Layer 1 (the property graph) answers "how often does this pattern occur". It cannot
answer "is this set of labels satisfiable", because unsatisfiability is not a pairwise
property: BEFORE(a,b) + BEFORE(b,c) + ENDS-ON(a,c) is contradictory while every pair in
it is fine. That question needs path consistency over interval relations, which is what
this module provides.

The composition table is generated by brute force over integer interval endpoints rather
than transcribed, because a hand-written Allen table is exactly the kind of artifact that
silently produces fake contradictions.

The MAVEN -> Allen mapping is the one settled in report/DEFINITIONS.md section B1.

Usage:
    python constraint_net.py --split train --limit 300
    python constraint_net.py --split train --self-test
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from itertools import product
from pathlib import Path

HERE = Path(__file__).resolve().parent

ROOT = Path(__file__).resolve().parent.parent

# Allen's 13 basic relations, named as usual.
#   b  before        bi  after
#   m  meets         mi  met-by
#   o  overlaps      oi  overlapped-by
#   s  starts        si  started-by
#   d  during        di  contains
#   f  finishes      fi  finished-by
#   e  equals
ALL13 = ("b", "bi", "m", "mi", "o", "oi", "s", "si", "d", "di", "f", "fi", "e")

CONVERSE = {"b": "bi", "bi": "b", "m": "mi", "mi": "m", "o": "oi", "oi": "o",
            "s": "si", "si": "s", "d": "di", "di": "d", "f": "fi", "fi": "f", "e": "e"}

# B1, settled: ENDS-ON is {b,m} not {m}; OVERLAP is {o} not {o,oi}.
MAVEN_TO_ALLEN = {
    "BEFORE":       frozenset({"b"}),
    "CONTAINS":     frozenset({"di"}),
    "OVERLAP":      frozenset({"o"}),
    "SIMULTANEOUS": frozenset({"e"}),
    "BEGINS-ON":    frozenset({"s", "si", "e"}),
    "ENDS-ON":      frozenset({"b", "m"}),
}

FULL = frozenset(ALL13)


def basic_relation(a: tuple, b: tuple) -> str:
    """Allen relation between two closed intervals given as (start, end), start < end."""
    (s1, e1), (s2, e2) = a, b
    if e1 < s2:
        return "b"
    if e1 == s2:
        return "m"
    if s1 == s2 and e1 == e2:
        return "e"
    if s1 == s2:
        return "s" if e1 < e2 else "si"
    if e1 == e2:
        return "f" if s1 > s2 else "fi"
    if s1 < s2 and e2 < e1:
        return "di"
    if s2 < s1 and e1 < e2:
        return "d"
    if s1 < s2 < e1 < e2:
        return "o"
    if s2 < s1 < e2 < e1:
        return "oi"
    if e2 == s1:
        return "mi"
    if e2 < s1:
        return "bi"
    raise AssertionError(f"unreachable: {a} {b}")


def build_composition_table(n: int = 7) -> dict:
    """comp[(r1, r2)] = set of r3 such that r1(x,y) and r2(y,z) admits r3(x,z).

    Enumerated over all non-degenerate integer intervals inside [0, n). Brute force so
    the table cannot disagree with basic_relation().
    """
    intervals = [(s, e) for s in range(n) for e in range(s + 1, n)]
    table = {(r1, r2): set() for r1 in ALL13 for r2 in ALL13}
    for x in intervals:
        for y in intervals:
            r1 = basic_relation(x, y)
            for z in intervals:
                table[(r1, basic_relation(y, z))].add(basic_relation(x, z))
    return {k: frozenset(v) for k, v in table.items()}


COMP = build_composition_table()


def compose(s1: frozenset, s2: frozenset) -> frozenset:
    out = set()
    for r1 in s1:
        for r2 in s2:
            out |= COMP[(r1, r2)]
    return frozenset(out)


def converse(s: frozenset) -> frozenset:
    return frozenset(CONVERSE[r] for r in s)


def path_consistency(nodes: list, constraints: dict):
    """PC-2 to fixpoint. Returns (consistent, matrix).

    Does NOT return early on the empty set: the matrix is needed even for inconsistent
    documents, both to locate the contradiction and to report which pairs were pinned.
    """
    idx = {n: i for i, n in enumerate(nodes)}
    k = len(nodes)
    m = [[FULL] * k for _ in range(k)]
    for i in range(k):
        m[i] = list(m[i])
        m[i][i] = frozenset({"e"})

    for (a, b), rel in constraints.items():
        i, j = idx[a], idx[b]
        m[i][j] = m[i][j] & rel
        m[j][i] = m[j][i] & converse(rel)

    queue = [(i, j) for i in range(k) for j in range(k) if i != j]
    consistent = True
    while queue:
        i, j = queue.pop()
        for x in range(k):
            if x in (i, j):
                continue
            new = m[i][x] & compose(m[i][j], m[j][x])
            if new != m[i][x]:
                if not new:
                    consistent = False
                m[i][x] = new
                m[x][i] = converse(new)
                queue.append((i, x))
            new = m[x][j] & compose(m[x][i], m[i][j])
            if new != m[x][j]:
                if not new:
                    consistent = False
                m[x][j] = new
                m[j][x] = converse(new)
                queue.append((x, j))
    return consistent, (idx, m)


def document_constraints(rec: dict, include_weak: bool = False) -> tuple:
    """Turn a built document into (nodes, constraints) for the constraint network.

    Only nodes that actually carry a temporal constraint are included -- an isolated
    node contributes nothing and makes PC quadratically slower for no reason.
    """
    constraints = {}
    for e in rec["target_edges"]:
        rel = MAVEN_TO_ALLEN.get(e["rel"])
        if rel is None:
            continue
        key = (e["s"], e["t"])
        constraints[key] = constraints.get(key, FULL) & rel

    if include_weak:
        # D1: causal is a weak prior, not independent evidence -- 95.2% of PRECONDITION
        # pairs already carry a temporal label. Off by default; available for ablation.
        for e in rec["weak_edges"]:
            if e["kind"] in ("CAUSE", "PRECONDITION"):
                implied = frozenset({"b", "m", "o"})
            elif e["kind"] == "SUBEVENT":
                implied = frozenset({"di", "si", "fi", "e"})
            else:
                continue
            key = (e["s"], e["t"])
            constraints[key] = constraints.get(key, FULL) & implied

    nodes = sorted({n for pair in constraints for n in pair})
    return nodes, constraints


def minimal_core(nodes: list, constraints: dict) -> list:
    """Smallest subset of constraints that is still inconsistent.

    Delete-one-and-retry: O(|constraints|) PC runs. Only called on documents already
    known to be inconsistent, which on gold is none and after injection is a few percent.
    """
    core = dict(constraints)
    for key in list(core):
        trial = {k: v for k, v in core.items() if k != key}
        if not trial:
            continue
        sub = sorted({n for pair in trial for n in pair})
        consistent, _ = path_consistency(sub, trial)
        if not consistent:
            core = trial
    return sorted(core)


def self_test() -> int:
    """The table and PC must agree with hand-checkable facts."""
    failures = []

    def check(name, cond):
        if not cond:
            failures.append(name)

    check("comp(b,b)={b}", COMP[("b", "b")] == frozenset({"b"}))
    check("comp(e,X)=X", all(COMP[("e", r)] == frozenset({r}) for r in ALL13))
    check("comp(X,e)=X", all(COMP[(r, "e")] == frozenset({r}) for r in ALL13))
    check("comp(b,bi)=full", COMP[("b", "bi")] == FULL)
    check("converse involution", all(CONVERSE[CONVERSE[r]] == r for r in ALL13))
    check("13 relations", len(ALL13) == 13 and len(set(ALL13)) == 13)

    # basic_relation must be total and consistent with its own converse
    ivs = [(s, e) for s in range(6) for e in range(s + 1, 6)]
    check("converse symmetry",
          all(CONVERSE[basic_relation(x, y)] == basic_relation(y, x) for x, y in product(ivs, ivs)))

    # the three-variable contradiction that a pairwise table cannot see
    nodes = ["a", "b", "c"]
    con = {("a", "b"): MAVEN_TO_ALLEN["BEFORE"],
           ("b", "c"): MAVEN_TO_ALLEN["BEFORE"],
           ("a", "c"): MAVEN_TO_ALLEN["ENDS-ON"]}
    ok, _ = path_consistency(nodes, con)
    check("BEFORE+BEFORE+ENDS-ON{b,m} is consistent", ok)

    # under the rejected mapping ENDS-ON={m} the same triple becomes inconsistent --
    # this is exactly the artifact that produced 7 fake contradictions in an earlier round
    con_m = dict(con)
    con_m[("a", "c")] = frozenset({"m"})
    ok_m, _ = path_consistency(nodes, con_m)
    check("BEFORE+BEFORE+ENDS-ON{m} is INconsistent", not ok_m)

    # a real contradiction must be caught
    cyc = {("a", "b"): MAVEN_TO_ALLEN["BEFORE"],
           ("b", "c"): MAVEN_TO_ALLEN["BEFORE"],
           ("c", "a"): MAVEN_TO_ALLEN["BEFORE"]}
    ok_cyc, _ = path_consistency(nodes, cyc)
    check("BEFORE cycle is INconsistent", not ok_cyc)

    # and a pairwise contradiction too
    pw = {("a", "b"): MAVEN_TO_ALLEN["BEFORE"] & MAVEN_TO_ALLEN["CONTAINS"]}
    check("BEFORE & CONTAINS is empty", not pw[("a", "b")])

    for name in failures:
        print(f"  FAIL  {name}")
    if failures:
        print(f"\n{len(failures)} self-test failures.")
        return 1
    print("  PASS  composition table (brute-forced, 13x13)")
    print("  PASS  converse involution and symmetry")
    print("  PASS  3-variable contradiction detected under ENDS-ON={m}")
    print("  PASS  3-variable consistency under ENDS-ON={b,m}  (the settled mapping)")
    print("  PASS  BEFORE cycle detected")
    print("\nSelf-test passed.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--split", default="train")
    ap.add_argument("--graph-dir", type=Path, default=HERE / "graph")
    ap.add_argument("--limit", type=int, default=300)
    ap.add_argument("--include-weak", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    import time
    path = args.graph_dir / f"{args.split}.jsonl"
    stats = Counter()
    sizes, times = [], []

    with path.open(encoding="utf-8") as fh:
        for i, line in enumerate(fh):
            if args.limit and i >= args.limit:
                break
            rec = json.loads(line)
            nodes, constraints = document_constraints(rec, args.include_weak)
            if len(nodes) < 2:
                stats["skipped_trivial"] += 1
                continue
            t0 = time.perf_counter()
            consistent, _ = path_consistency(nodes, constraints)
            times.append(time.perf_counter() - t0)
            sizes.append((len(nodes), len(constraints)))
            stats["consistent" if consistent else "INCONSISTENT"] += 1

    print(f"documents tested       {sum(stats[k] for k in ('consistent', 'INCONSISTENT')):,}")
    print(f"  consistent           {stats['consistent']:,}")
    print(f"  INCONSISTENT         {stats['INCONSISTENT']:,}")
    print(f"  skipped (<2 nodes)   {stats['skipped_trivial']:,}")
    if sizes:
        ns = sorted(n for n, _ in sizes)
        cs = sorted(c for _, c in sizes)
        ts = sorted(times)
        print(f"\nnodes per network      median {ns[len(ns)//2]}  max {ns[-1]}")
        print(f"constraints per net    median {cs[len(cs)//2]}  max {cs[-1]}")
        print(f"PC runtime (s)         median {ts[len(ts)//2]:.4f}  max {ts[-1]:.3f}  total {sum(times):.1f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
